// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXBvRRkld0wYW4GXeiKiW9_Lf0e8n0ozY',
    appId: '1:360214200595:android:c2653084e7425911885ae6',
    messagingSenderId: '360214200595',
    projectId: 'sehirli-17894',
    storageBucket: 'sehirli-17894.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtUojw5Vwkica9zzZ4q2FVvkckf6KCBwY',
    appId: '1:360214200595:ios:92cba02f756feb5a885ae6',
    messagingSenderId: '360214200595',
    projectId: 'sehirli-17894',
    storageBucket: 'sehirli-17894.appspot.com',
    androidClientId: '360214200595-1rleq7ekp9qaq4edro7u62cf3ahon2gf.apps.googleusercontent.com',
    iosClientId: '360214200595-fd74l4eqhapo0lv347coi2rhkq9m6kgh.apps.googleusercontent.com',
    iosBundleId: 'com.emirs.sehirli',
  );
}
